### ISSUE TITLE
TypeError: transformer_1.HtmlTransformer is not a constructor

### ISSUE THREAD

**Issue by Bikossor** [Bikossor/codestain#87]
```
D:\Git\codestain\dist\factories\TransformerFactory.js:8
            return new transformer_1.HtmlTransformer();
                   ^

TypeError: transformer_1.HtmlTransformer is not a constructor
    at Object.createTransformer (D:\Git\codestain\dist\factories\TransformerFactory.js:8:20)
    at Codestain (D:\Git\codestain\dist\Codestain.js:10:37)
    at Object.<anonymous> (D:\Git\codestain\main.js:33:5)
```

**Comment by Bikossor** [comment]
The problem was that my local `/dist` folder wasn't getting cleaned up before building so I had a leftover `transformer.ts` file in it which confused the `import { HtmlTransformer } from "../transformer";` of the `TransformerFactory.ts` (it imported the `transformer.ts` file itself rather than the folder called `transformer`).
